# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BaseRNTypescript' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for BaseRNTypescript

  target 'BaseRNTypescript-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BaseRNTypescriptTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'BaseRNTypescript-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for BaseRNTypescript-tvOS

  target 'BaseRNTypescript-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
