export const DEVICE_DATA_CHANGE = 'DEVICE_DATA_CHANGE';
export const DEVICE_KEY_ADDED = 'DEVICE_KEY_ADDED';
export const NOTIFICATION_RECEIVED = 'NOTIFICATION_RECEIVED';
export const LOGOUT = 'LOGOUT';
